GET http://localhost:3000/blogs 
content-type: application/json

####

GET http://localhost:3000/blogpost 
content-type: application/json

{
    "ref": 4
}

####

GET http://localhost:3000/blogfilter
content-type: application/json

{
    "theme": "Mentorship"
}

####

GET http://localhost:3000/blogthemes 
content-type: application/json